### ISSUE TITLE
Feature roadmap for TMEA

### ISSUE THREAD

**Issue by kMutagene** [CSBiology/TMEA#1]
While this package already contains everything needed for performing TMEA, there are many things that can and should be ported from our internal analysis scripts that we used to prepare our paper. Users of this library can expect the following features to be added over time:

**General**:
 - [x] better result types as input for various functions (added via cc32d3962271408104775ef5150068d1ee086503 )
 - [x] namespace cleanup (shorter and more concise namespaces) (added via cc32d3962271408104775ef5150068d1ee086503 )

**Plots:**
 - [x] Visualizations for Surprisal Analysis results: constraint potential time course and free energy landscape (added via 121138f952f9caf505bb31952a1389a96f185a72)
 - [x] Surprisal Analysis: constraint potential heatmap (added via 1be3084495861b86064981634945b9bd234b2ea4)
 - [x] Surprisal Analysis: plots for supporting selection of constraints that are important (visualizing Singular Values and data reconstruction) (added via eef8d551bc936e1799172fbe91ed3018a126dee1)
 - [ ] Analytical plots for the TMEA result e.g. p value distribution, 
 - [ ] Set comparison (either via venn or chord diagrams, maybe add upset plot support)
 - [x] Weight distributions of single entities in the dataset across constraints (added via c8dccac02ce11ba4c5091a56f74638d4ad8e056a)

**Frames**:
 - [ ] Frames suitable for fast comparison of significant entities in the TMEA result

**Additional dev tooling (moved to #2)**

**Comment by kMutagene** [comment]
p-value distribution and set comparison will be added when potential users see the need for it.
